/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author otorradomiguez
 */
public class pruebasLayout extends javax.swing.JPanel {

    /**
     * Creates new form pruebasLayout
     */
    public pruebasLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new javax.swing.OverlayLayout(this));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maagic/img/logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maagic/img/ImagenFondo.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
