/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maagic.interfaz;

import java.awt.BorderLayout;

/**
 *
 * @author Delio
 */
public class Baraja extends javax.swing.JPanel {

    /**
     * Creates new form Baraja
     */
    public Baraja() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        PasoaCargarJugador2 = new javax.swing.JButton();
        RetornoMenu = new javax.swing.JButton();
        GuardarBaraja = new javax.swing.JButton();
        panelvolvermenu=new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1566, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 291, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1374, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );
        javax.swing.GroupLayout jPanel3Layout=new javax.swing.GroupLayout(panelvolvermenu);
        panelvolvermenu.setLayout(jPanel3Layout);
         jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1374, Short.MAX_VALUE));
         jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );

        PasoaCargarJugador2.setBackground(new java.awt.Color(0, 153, 153));
        PasoaCargarJugador2.setFont(new java.awt.Font("Felix Titling", 0, 11)); // NOI18N
        PasoaCargarJugador2.setForeground(new java.awt.Color(51, 0, 153));
        PasoaCargarJugador2.setText("Cargar Baraja");
        PasoaCargarJugador2.setToolTipText("");
        PasoaCargarJugador2.setBorder(null);
        PasoaCargarJugador2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PasoaCargarJugador2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        RetornoMenu.setBackground(new java.awt.Color(0, 153, 153));
        RetornoMenu.setFont(new java.awt.Font("Felix Titling", 0, 11)); // NOI18N
        RetornoMenu.setForeground(new java.awt.Color(153, 0, 0));
        RetornoMenu.setText("Volver");
        RetornoMenu.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetornoMenuActionPerformed(evt);
            }
        });

        GuardarBaraja.setBackground(new java.awt.Color(0, 153, 153));
        GuardarBaraja.setFont(new java.awt.Font("Felix Titling", 0, 11)); // NOI18N
        GuardarBaraja.setText("Guardar Baraja");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(632, 632, 632)
                        .addComponent(PasoaCargarJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(733, 733, 733)
                        .addComponent(RetornoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(613, 613, 613)
                        .addComponent(GuardarBaraja, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(GuardarBaraja, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(PasoaCargarJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(RetornoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
         
    }// </editor-fold>//GEN-END:initComponents
private void RetornoMenuActionPerformed(java.awt.event.ActionEvent evt) {  
Menu VolverMenu =new Menu();
VolverMenu.setSize(1920, 1080);
panelvolvermenu.setVisible(true);
panelvolvermenu.add(VolverMenu, BorderLayout.CENTER);
panelvolvermenu.revalidate();
panelvolvermenu.repaint();




}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GuardarBaraja;
    private javax.swing.JButton PasoaCargarJugador2;
    private javax.swing.JButton RetornoMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelvolvermenu;
    // End of variables declaration//GEN-END:variables
}
