/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maagic.interfaz;

import maagic.Carta;

/**
 *
 * @author Delio
 */
public class CartaInterfad extends javax.swing.JPanel {

    /**
     * Creates new form Carta
     */
    public CartaInterfad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Variable1Vida = new javax.swing.JLabel();
        Variable2Ataque = new javax.swing.JLabel();
        Variable3Coste = new javax.swing.JLabel();
        Vida = new javax.swing.JLabel();
        Ataque = new javax.swing.JLabel();
        Coste = new javax.swing.JLabel();
        ImagenesFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Variable1Vida.setText("GetVida");
        add(Variable1Vida, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        Variable2Ataque.setText("GetAtaque");
        add(Variable2Ataque, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        Variable3Coste.setText("GetCoste");
        add(Variable3Coste, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        Vida.setText("Vida");
        add(Vida, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        Ataque.setText("Ataque");
        add(Ataque, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        Coste.setText("Coste");
        add(Coste, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        ImagenesFondo.setText("jLabel1");
        add(ImagenesFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 310));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ataque;
    private javax.swing.JLabel Coste;
    private javax.swing.JLabel ImagenesFondo;
    private javax.swing.JLabel Variable1Vida;
    private javax.swing.JLabel Variable2Ataque;
    private javax.swing.JLabel Variable3Coste;
    private javax.swing.JLabel Vida;
    // End of variables declaration//GEN-END:variables
}
