/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maagic.interfaz;

/**
 *
 * @author Orom
 */
public class Interfaz2 extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jugador1Baraja = new javax.swing.JPanel();
        jugador1Corazon = new javax.swing.JPanel();
        jugador1Gema = new javax.swing.JPanel();
        jugador1Mana = new javax.swing.JPanel();
        jugador1Vida = new javax.swing.JPanel();
        jugador2Baraja = new javax.swing.JPanel();
        jugador2Corazon = new javax.swing.JPanel();
        jugador2Gema = new javax.swing.JPanel();
        jugador2Vida = new javax.swing.JPanel();
        jugador2Mana = new javax.swing.JPanel();
        jugador1Mano1 = new javax.swing.JPanel();
        jugador1Mano2 = new javax.swing.JPanel();
        jugador1Mano3 = new javax.swing.JPanel();
        jugador1Fila2Hueco1 = new javax.swing.JPanel();
        jugador1Fila1Hueco1 = new javax.swing.JPanel();
        jugador1Fila1Hueco2 = new javax.swing.JPanel();
        jugador1Fila1Hueco3 = new javax.swing.JPanel();
        jugador2Fila1Hueco3 = new javax.swing.JPanel();
        jugador2Fila1Hueco2 = new javax.swing.JPanel();
        jugador2Fila1Hueco1 = new javax.swing.JPanel();
        jugador2Mano1 = new javax.swing.JPanel();
        jugador2Mano3 = new javax.swing.JPanel();
        jugador2Fila3Hueco1 = new javax.swing.JPanel();
        jugador2Fila3Hueco2 = new javax.swing.JPanel();
        jugador2Fila3Hueco3 = new javax.swing.JPanel();
        jugador1Fila3Hueco3 = new javax.swing.JPanel();
        jugador1Fila3Hueco2 = new javax.swing.JPanel();
        jugador1Fila2Hueco2 = new javax.swing.JPanel();
        jugador1Fila2Hueco3 = new javax.swing.JPanel();
        jugador2Fila2Hueco3 = new javax.swing.JPanel();
        jugador2Fila2Hueco2 = new javax.swing.JPanel();
        jugador2Fila2Hueco1 = new javax.swing.JPanel();
        jugador2Mano2 = new javax.swing.JPanel();
        jugador1Fila3Hueco1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jugador1BarajaLayout = new javax.swing.GroupLayout(jugador1Baraja);
        jugador1Baraja.setLayout(jugador1BarajaLayout);
        jugador1BarajaLayout.setHorizontalGroup(
            jugador1BarajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );
        jugador1BarajaLayout.setVerticalGroup(
            jugador1BarajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador1CorazonLayout = new javax.swing.GroupLayout(jugador1Corazon);
        jugador1Corazon.setLayout(jugador1CorazonLayout);
        jugador1CorazonLayout.setHorizontalGroup(
            jugador1CorazonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jugador1CorazonLayout.setVerticalGroup(
            jugador1CorazonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador1GemaLayout = new javax.swing.GroupLayout(jugador1Gema);
        jugador1Gema.setLayout(jugador1GemaLayout);
        jugador1GemaLayout.setHorizontalGroup(
            jugador1GemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );
        jugador1GemaLayout.setVerticalGroup(
            jugador1GemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador1ManaLayout = new javax.swing.GroupLayout(jugador1Mana);
        jugador1Mana.setLayout(jugador1ManaLayout);
        jugador1ManaLayout.setHorizontalGroup(
            jugador1ManaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );
        jugador1ManaLayout.setVerticalGroup(
            jugador1ManaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador1VidaLayout = new javax.swing.GroupLayout(jugador1Vida);
        jugador1Vida.setLayout(jugador1VidaLayout);
        jugador1VidaLayout.setHorizontalGroup(
            jugador1VidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );
        jugador1VidaLayout.setVerticalGroup(
            jugador1VidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador2BarajaLayout = new javax.swing.GroupLayout(jugador2Baraja);
        jugador2Baraja.setLayout(jugador2BarajaLayout);
        jugador2BarajaLayout.setHorizontalGroup(
            jugador2BarajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );
        jugador2BarajaLayout.setVerticalGroup(
            jugador2BarajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador2CorazonLayout = new javax.swing.GroupLayout(jugador2Corazon);
        jugador2Corazon.setLayout(jugador2CorazonLayout);
        jugador2CorazonLayout.setHorizontalGroup(
            jugador2CorazonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );
        jugador2CorazonLayout.setVerticalGroup(
            jugador2CorazonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador2GemaLayout = new javax.swing.GroupLayout(jugador2Gema);
        jugador2Gema.setLayout(jugador2GemaLayout);
        jugador2GemaLayout.setHorizontalGroup(
            jugador2GemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );
        jugador2GemaLayout.setVerticalGroup(
            jugador2GemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador2VidaLayout = new javax.swing.GroupLayout(jugador2Vida);
        jugador2Vida.setLayout(jugador2VidaLayout);
        jugador2VidaLayout.setHorizontalGroup(
            jugador2VidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jugador2VidaLayout.setVerticalGroup(
            jugador2VidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador2ManaLayout = new javax.swing.GroupLayout(jugador2Mana);
        jugador2Mana.setLayout(jugador2ManaLayout);
        jugador2ManaLayout.setHorizontalGroup(
            jugador2ManaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 87, Short.MAX_VALUE)
        );
        jugador2ManaLayout.setVerticalGroup(
            jugador2ManaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador1Mano1Layout = new javax.swing.GroupLayout(jugador1Mano1);
        jugador1Mano1.setLayout(jugador1Mano1Layout);
        jugador1Mano1Layout.setHorizontalGroup(
            jugador1Mano1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jugador1Mano1Layout.setVerticalGroup(
            jugador1Mano1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador1Mano2Layout = new javax.swing.GroupLayout(jugador1Mano2);
        jugador1Mano2.setLayout(jugador1Mano2Layout);
        jugador1Mano2Layout.setHorizontalGroup(
            jugador1Mano2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );
        jugador1Mano2Layout.setVerticalGroup(
            jugador1Mano2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador1Mano3Layout = new javax.swing.GroupLayout(jugador1Mano3);
        jugador1Mano3.setLayout(jugador1Mano3Layout);
        jugador1Mano3Layout.setHorizontalGroup(
            jugador1Mano3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jugador1Mano3Layout.setVerticalGroup(
            jugador1Mano3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador1Fila2Hueco1Layout = new javax.swing.GroupLayout(jugador1Fila2Hueco1);
        jugador1Fila2Hueco1.setLayout(jugador1Fila2Hueco1Layout);
        jugador1Fila2Hueco1Layout.setHorizontalGroup(
            jugador1Fila2Hueco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );
        jugador1Fila2Hueco1Layout.setVerticalGroup(
            jugador1Fila2Hueco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador1Fila1Hueco1Layout = new javax.swing.GroupLayout(jugador1Fila1Hueco1);
        jugador1Fila1Hueco1.setLayout(jugador1Fila1Hueco1Layout);
        jugador1Fila1Hueco1Layout.setHorizontalGroup(
            jugador1Fila1Hueco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jugador1Fila1Hueco1Layout.setVerticalGroup(
            jugador1Fila1Hueco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador1Fila1Hueco2Layout = new javax.swing.GroupLayout(jugador1Fila1Hueco2);
        jugador1Fila1Hueco2.setLayout(jugador1Fila1Hueco2Layout);
        jugador1Fila1Hueco2Layout.setHorizontalGroup(
            jugador1Fila1Hueco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jugador1Fila1Hueco2Layout.setVerticalGroup(
            jugador1Fila1Hueco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador1Fila1Hueco3Layout = new javax.swing.GroupLayout(jugador1Fila1Hueco3);
        jugador1Fila1Hueco3.setLayout(jugador1Fila1Hueco3Layout);
        jugador1Fila1Hueco3Layout.setHorizontalGroup(
            jugador1Fila1Hueco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jugador1Fila1Hueco3Layout.setVerticalGroup(
            jugador1Fila1Hueco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador2Fila1Hueco3Layout = new javax.swing.GroupLayout(jugador2Fila1Hueco3);
        jugador2Fila1Hueco3.setLayout(jugador2Fila1Hueco3Layout);
        jugador2Fila1Hueco3Layout.setHorizontalGroup(
            jugador2Fila1Hueco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jugador2Fila1Hueco3Layout.setVerticalGroup(
            jugador2Fila1Hueco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador2Fila1Hueco2Layout = new javax.swing.GroupLayout(jugador2Fila1Hueco2);
        jugador2Fila1Hueco2.setLayout(jugador2Fila1Hueco2Layout);
        jugador2Fila1Hueco2Layout.setHorizontalGroup(
            jugador2Fila1Hueco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jugador2Fila1Hueco2Layout.setVerticalGroup(
            jugador2Fila1Hueco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador2Fila1Hueco1Layout = new javax.swing.GroupLayout(jugador2Fila1Hueco1);
        jugador2Fila1Hueco1.setLayout(jugador2Fila1Hueco1Layout);
        jugador2Fila1Hueco1Layout.setHorizontalGroup(
            jugador2Fila1Hueco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jugador2Fila1Hueco1Layout.setVerticalGroup(
            jugador2Fila1Hueco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador2Mano1Layout = new javax.swing.GroupLayout(jugador2Mano1);
        jugador2Mano1.setLayout(jugador2Mano1Layout);
        jugador2Mano1Layout.setHorizontalGroup(
            jugador2Mano1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jugador2Mano1Layout.setVerticalGroup(
            jugador2Mano1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador2Mano3Layout = new javax.swing.GroupLayout(jugador2Mano3);
        jugador2Mano3.setLayout(jugador2Mano3Layout);
        jugador2Mano3Layout.setHorizontalGroup(
            jugador2Mano3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jugador2Mano3Layout.setVerticalGroup(
            jugador2Mano3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador2Fila3Hueco1Layout = new javax.swing.GroupLayout(jugador2Fila3Hueco1);
        jugador2Fila3Hueco1.setLayout(jugador2Fila3Hueco1Layout);
        jugador2Fila3Hueco1Layout.setHorizontalGroup(
            jugador2Fila3Hueco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jugador2Fila3Hueco1Layout.setVerticalGroup(
            jugador2Fila3Hueco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador2Fila3Hueco2Layout = new javax.swing.GroupLayout(jugador2Fila3Hueco2);
        jugador2Fila3Hueco2.setLayout(jugador2Fila3Hueco2Layout);
        jugador2Fila3Hueco2Layout.setHorizontalGroup(
            jugador2Fila3Hueco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jugador2Fila3Hueco2Layout.setVerticalGroup(
            jugador2Fila3Hueco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador2Fila3Hueco3Layout = new javax.swing.GroupLayout(jugador2Fila3Hueco3);
        jugador2Fila3Hueco3.setLayout(jugador2Fila3Hueco3Layout);
        jugador2Fila3Hueco3Layout.setHorizontalGroup(
            jugador2Fila3Hueco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jugador2Fila3Hueco3Layout.setVerticalGroup(
            jugador2Fila3Hueco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador1Fila3Hueco3Layout = new javax.swing.GroupLayout(jugador1Fila3Hueco3);
        jugador1Fila3Hueco3.setLayout(jugador1Fila3Hueco3Layout);
        jugador1Fila3Hueco3Layout.setHorizontalGroup(
            jugador1Fila3Hueco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jugador1Fila3Hueco3Layout.setVerticalGroup(
            jugador1Fila3Hueco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador1Fila3Hueco2Layout = new javax.swing.GroupLayout(jugador1Fila3Hueco2);
        jugador1Fila3Hueco2.setLayout(jugador1Fila3Hueco2Layout);
        jugador1Fila3Hueco2Layout.setHorizontalGroup(
            jugador1Fila3Hueco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jugador1Fila3Hueco2Layout.setVerticalGroup(
            jugador1Fila3Hueco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador1Fila2Hueco2Layout = new javax.swing.GroupLayout(jugador1Fila2Hueco2);
        jugador1Fila2Hueco2.setLayout(jugador1Fila2Hueco2Layout);
        jugador1Fila2Hueco2Layout.setHorizontalGroup(
            jugador1Fila2Hueco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jugador1Fila2Hueco2Layout.setVerticalGroup(
            jugador1Fila2Hueco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador1Fila2Hueco3Layout = new javax.swing.GroupLayout(jugador1Fila2Hueco3);
        jugador1Fila2Hueco3.setLayout(jugador1Fila2Hueco3Layout);
        jugador1Fila2Hueco3Layout.setHorizontalGroup(
            jugador1Fila2Hueco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );
        jugador1Fila2Hueco3Layout.setVerticalGroup(
            jugador1Fila2Hueco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador2Fila2Hueco3Layout = new javax.swing.GroupLayout(jugador2Fila2Hueco3);
        jugador2Fila2Hueco3.setLayout(jugador2Fila2Hueco3Layout);
        jugador2Fila2Hueco3Layout.setHorizontalGroup(
            jugador2Fila2Hueco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jugador2Fila2Hueco3Layout.setVerticalGroup(
            jugador2Fila2Hueco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador2Fila2Hueco2Layout = new javax.swing.GroupLayout(jugador2Fila2Hueco2);
        jugador2Fila2Hueco2.setLayout(jugador2Fila2Hueco2Layout);
        jugador2Fila2Hueco2Layout.setHorizontalGroup(
            jugador2Fila2Hueco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jugador2Fila2Hueco2Layout.setVerticalGroup(
            jugador2Fila2Hueco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador2Fila2Hueco1Layout = new javax.swing.GroupLayout(jugador2Fila2Hueco1);
        jugador2Fila2Hueco1.setLayout(jugador2Fila2Hueco1Layout);
        jugador2Fila2Hueco1Layout.setHorizontalGroup(
            jugador2Fila2Hueco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jugador2Fila2Hueco1Layout.setVerticalGroup(
            jugador2Fila2Hueco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador2Mano2Layout = new javax.swing.GroupLayout(jugador2Mano2);
        jugador2Mano2.setLayout(jugador2Mano2Layout);
        jugador2Mano2Layout.setHorizontalGroup(
            jugador2Mano2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jugador2Mano2Layout.setVerticalGroup(
            jugador2Mano2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jugador1Fila3Hueco1Layout = new javax.swing.GroupLayout(jugador1Fila3Hueco1);
        jugador1Fila3Hueco1.setLayout(jugador1Fila3Hueco1Layout);
        jugador1Fila3Hueco1Layout.setHorizontalGroup(
            jugador1Fila3Hueco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jugador1Fila3Hueco1Layout.setVerticalGroup(
            jugador1Fila3Hueco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jugador1Baraja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jugador1Gema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jugador1Corazon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jugador1Mana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jugador1Vida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(397, 397, 397)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jugador2Vida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jugador2Corazon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jugador2Mana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jugador2Gema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jugador2Baraja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jugador1Mano3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jugador1Mano1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jugador1Mano2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jugador1Fila1Hueco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jugador1Fila1Hueco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jugador1Fila1Hueco3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jugador1Fila2Hueco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jugador1Fila2Hueco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jugador1Fila2Hueco3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jugador2Fila1Hueco3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jugador2Fila1Hueco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jugador2Fila1Hueco1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jugador2Fila2Hueco3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jugador2Fila2Hueco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jugador2Fila2Hueco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jugador1Fila3Hueco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jugador1Fila3Hueco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jugador1Fila3Hueco3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jugador2Fila3Hueco3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jugador2Fila3Hueco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jugador2Fila3Hueco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jugador2Mano2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jugador2Mano1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jugador2Mano3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jugador1Corazon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jugador1Vida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jugador1Gema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jugador1Mana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jugador2Baraja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jugador2Corazon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jugador2Vida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jugador2Gema, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jugador2Mana, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jugador1Baraja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jugador2Mano1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugador2Fila1Hueco1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugador2Fila1Hueco2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugador2Fila1Hueco3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugador1Fila1Hueco3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugador1Fila1Hueco2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugador1Mano1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugador1Fila1Hueco1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jugador2Fila2Hueco1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugador2Fila2Hueco2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugador2Fila2Hueco3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugador1Fila2Hueco3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugador1Fila2Hueco2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugador1Fila2Hueco1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugador1Mano2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugador2Mano2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jugador1Fila3Hueco2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugador1Fila3Hueco3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugador2Fila3Hueco3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugador2Fila3Hueco2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugador2Fila3Hueco1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugador2Mano3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugador1Mano3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugador1Fila3Hueco1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(140, 140, 140))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jugador1Baraja;
    private javax.swing.JPanel jugador1Corazon;
    private javax.swing.JPanel jugador1Fila1Hueco1;
    private javax.swing.JPanel jugador1Fila1Hueco2;
    private javax.swing.JPanel jugador1Fila1Hueco3;
    private javax.swing.JPanel jugador1Fila2Hueco1;
    private javax.swing.JPanel jugador1Fila2Hueco2;
    private javax.swing.JPanel jugador1Fila2Hueco3;
    private javax.swing.JPanel jugador1Fila3Hueco1;
    private javax.swing.JPanel jugador1Fila3Hueco2;
    private javax.swing.JPanel jugador1Fila3Hueco3;
    private javax.swing.JPanel jugador1Gema;
    private javax.swing.JPanel jugador1Mana;
    private javax.swing.JPanel jugador1Mano1;
    private javax.swing.JPanel jugador1Mano2;
    private javax.swing.JPanel jugador1Mano3;
    private javax.swing.JPanel jugador1Vida;
    private javax.swing.JPanel jugador2Baraja;
    private javax.swing.JPanel jugador2Corazon;
    private javax.swing.JPanel jugador2Fila1Hueco1;
    private javax.swing.JPanel jugador2Fila1Hueco2;
    private javax.swing.JPanel jugador2Fila1Hueco3;
    private javax.swing.JPanel jugador2Fila2Hueco1;
    private javax.swing.JPanel jugador2Fila2Hueco2;
    private javax.swing.JPanel jugador2Fila2Hueco3;
    private javax.swing.JPanel jugador2Fila3Hueco1;
    private javax.swing.JPanel jugador2Fila3Hueco2;
    private javax.swing.JPanel jugador2Fila3Hueco3;
    private javax.swing.JPanel jugador2Gema;
    private javax.swing.JPanel jugador2Mana;
    private javax.swing.JPanel jugador2Mano1;
    private javax.swing.JPanel jugador2Mano2;
    private javax.swing.JPanel jugador2Mano3;
    private javax.swing.JPanel jugador2Vida;
    // End of variables declaration//GEN-END:variables
}
