/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maagic.interfaz;

import javafx.scene.control.ComboBox;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Delio
 */
public class InterfadSeleccionfinal extends javax.swing.JPanel {

    /**
     * Creates new form InterfadSeleccionfinal
     */
    public InterfadSeleccionfinal() {
        initComponents();
        MetodosBaseDatos metodos=new MetodosBaseDatos();
        metodos.seleccionarjugadores();
//        System.out.println(metodos.seleccionarjugadores());
        DefaultComboBoxModel modelo1 = new DefaultComboBoxModel();
        seleccionarjugadorj1.setModel(modelo1);
        modelo1.addElement(MetodosBaseDatos.nombres.get(0));
        modelo1.addElement(MetodosBaseDatos.nombres.get(1));
        DefaultComboBoxModel modelo2 = new DefaultComboBoxModel();
        seleccionarjugadorj2.setModel(modelo2);
        modelo2.addElement(MetodosBaseDatos.nombres.get(0));
        modelo2.addElement(MetodosBaseDatos.nombres.get(1));
        DefaultComboBoxModel modelo3 = new DefaultComboBoxModel();
//        seleccionarbarajaj1.setModel(modelo3);
//        modelo3.addElement(MetodosBaseDatos.barajas.get(0));
//        modelo3.addElement(MetodosBaseDatos.barajas.get(1));
//        DefaultComboBoxModel modelo4 = new DefaultComboBoxModel();
//        seleccionarbarajaj2.setModel(modelo4);
//        modelo4.addElement(MetodosBaseDatos.barajas.get(0));
//        modelo4.addElement(MetodosBaseDatos.barajas.get(1));
//        modelo2.addElement(metodos.seleccionarjugadores());
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionarjugadorj1 = new javax.swing.JComboBox<>();
        seleccionarjugadorj2 = new javax.swing.JComboBox<>();
        seleccionarj1 = new javax.swing.JButton();
        seleccionarj2 = new javax.swing.JButton();
        jugar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        seleccionarbarajaj2 = new javax.swing.JComboBox<>();
        seleccionarbarajaj1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        seleccionarjugadorj1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(seleccionarjugadorj1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 130, 39));

        seleccionarjugadorj2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(seleccionarjugadorj2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 117, 41));

        seleccionarj1.setText("Seleccionar");
        seleccionarj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarj1ActionPerformed(evt);
            }
        });
        add(seleccionarj1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        seleccionarj2.setText("Seleccionar");
        seleccionarj2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarj2ActionPerformed(evt);
            }
        });
        add(seleccionarj2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        jugar.setText("Jugar");
        jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugarActionPerformed(evt);
            }
        });
        add(jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, -1));

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, -1, -1));

        seleccionarbarajaj2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(seleccionarbarajaj2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 121, 41));

        seleccionarbarajaj1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(seleccionarbarajaj1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 121, 39));

        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionarj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarj1ActionPerformed
       if(seleccionarjugadorj1.getSelectedItem()==MetodosBaseDatos.nombres.get(0) ){
       System.out.println("Se ha seleccionado el jugador1");
       
       }
       else if (seleccionarjugadorj1.getSelectedItem()==MetodosBaseDatos.nombres.get(1)){
           System.out.println("Se ha seleccionado el jugador2");
           
       }
       
           
    }//GEN-LAST:event_seleccionarj1ActionPerformed

    private void seleccionarj2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarj2ActionPerformed
        if(seleccionarjugadorj2.getSelectedItem()==MetodosBaseDatos.nombres.get(0)){
       System.out.println("Se ha seleccionado el jugador1");
       
       }
       else if (seleccionarjugadorj2.getSelectedItem()==MetodosBaseDatos.nombres.get(1)){
           System.out.println("Se ha seleccionado el jugador2");
           
       }
       
    }//GEN-LAST:event_seleccionarj2ActionPerformed

    private void jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jugarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jugar;
    private javax.swing.JButton salir;
    private javax.swing.JComboBox<String> seleccionarbarajaj1;
    private javax.swing.JComboBox<String> seleccionarbarajaj2;
    private javax.swing.JButton seleccionarj1;
    private javax.swing.JButton seleccionarj2;
    private javax.swing.JComboBox<String> seleccionarjugadorj1;
    private javax.swing.JComboBox<String> seleccionarjugadorj2;
    // End of variables declaration//GEN-END:variables
}
