/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maagic.interfaz;

/**
 *
 * @author Delio
 */
public class InterfadSeleccionfinal extends javax.swing.JPanel {

    /**
     * Creates new form InterfadSeleccionfinal
     */
    public InterfadSeleccionfinal() {
        initComponents();
        MetodosBaseDatos metodos=new MetodosBaseDatos();
//        seleccionarjugadorj1.setSelectedItem(metodos.);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionarjugadorj1 = new javax.swing.JComboBox<>();
        seleccionarjugadorj2 = new javax.swing.JComboBox<>();
        seleccionarj1 = new javax.swing.JButton();
        cancelarj1 = new javax.swing.JButton();
        crearJugador = new javax.swing.JButton();
        seleccionarj2 = new javax.swing.JButton();
        cancelarj2 = new javax.swing.JButton();
        jugar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        seleccionarbarajaj2 = new javax.swing.JComboBox<>();
        seleccionarbarajaj1 = new javax.swing.JComboBox<>();

        seleccionarjugadorj1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        seleccionarjugadorj2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        seleccionarj1.setText("Seleccionar");
        seleccionarj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarj1ActionPerformed(evt);
            }
        });

        cancelarj1.setText("Cancelar");
        cancelarj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarj1ActionPerformed(evt);
            }
        });

        crearJugador.setText("Crear Jugador");
        crearJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearJugadorActionPerformed(evt);
            }
        });

        seleccionarj2.setText("Seleccionar");
        seleccionarj2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarj2ActionPerformed(evt);
            }
        });

        cancelarj2.setText("Cancelar");
        cancelarj2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarj2ActionPerformed(evt);
            }
        });

        jugar.setText("Jugar");
        jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugarActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        seleccionarbarajaj2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        seleccionarbarajaj1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jugar)
                        .addGap(123, 123, 123)
                        .addComponent(salir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(crearJugador)
                            .addComponent(borrar))))
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(seleccionarjugadorj1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seleccionarj1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seleccionarbarajaj1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelarj1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(seleccionarjugadorj2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(seleccionarbarajaj2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(seleccionarj2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelarj2)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crearJugador)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seleccionarjugadorj1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seleccionarbarajaj1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seleccionarj1)
                    .addComponent(cancelarj1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(seleccionarjugadorj2, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(seleccionarbarajaj2))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seleccionarj2)
                    .addComponent(cancelarj2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jugar)
                    .addComponent(salir))
                .addGap(9, 9, 9)
                .addComponent(borrar))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionarj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarj1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionarj1ActionPerformed

    private void crearJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearJugadorActionPerformed

    private void cancelarj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarj1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarj1ActionPerformed

    private void seleccionarj2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarj2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionarj2ActionPerformed

    private void cancelarj2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarj2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarj2ActionPerformed

    private void jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jugarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_borrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar;
    private javax.swing.JButton cancelarj1;
    private javax.swing.JButton cancelarj2;
    private javax.swing.JButton crearJugador;
    private javax.swing.JButton jugar;
    private javax.swing.JButton salir;
    private javax.swing.JComboBox<String> seleccionarbarajaj1;
    private javax.swing.JComboBox<String> seleccionarbarajaj2;
    private javax.swing.JButton seleccionarj1;
    private javax.swing.JButton seleccionarj2;
    private javax.swing.JComboBox<String> seleccionarjugadorj1;
    private javax.swing.JComboBox<String> seleccionarjugadorj2;
    // End of variables declaration//GEN-END:variables
}
