/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maagic.interfaz;

import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Delio
 */
public class JuegoPruevas extends javax.swing.JPanel {

    /**
     * Creates new form Juego
     * @throws java.sql.SQLException
     */
    public JuegoPruevas() throws SQLException, ClassNotFoundException {
        initComponents();
        //Cargamos el driver JDBC para sqlite (Esta en la libreria)
        Class.forName("org.sqlite.JDBC");
          Connection conexion;
          //Establecemos una conexion (Como no existe la DB creara una)
          conexion = DriverManager.getConnection("jdbc:sqlite:bdpruebas.db");
          //Instanciamos un Statement (Para realizar consultas, etc)
          java.sql.Statement st=conexion.createStatement();
           //A partir de aqui interactuamos con la BD usando el statement
            st.executeUpdate("DROP table Cartas");//Hacemos el drop pq si la tabla ya existe da error
            st.executeUpdate("CREATE table Cartas(id integer, nombre varchar, valorataque integer, valormana integer, valorvida integer)");//Creamos una tabla
            
            st.executeUpdate("INSERT into Cartas(1,Carta1,5,2,7)");
            st.executeUpdate("INSERT into Cartas(2,Carta2,7,3,4)");
            //Realizamos una consulta para que nos coja todos los datos
            ResultSet Cartastotales=st.executeQuery("SELECT * from Cartas");
            //realizamos un while para que nos muestre por pantalla todas las cartas
            while(Cartastotales.next()){
                //Mostramos la informacion de forma ordenada con un System.out.println para comprobar que funciona
        System.out.println("ID"+Cartastotales.getInt("id")+"Nombre de la carta"+Cartastotales.getString("nombre")+"Ataque"+Cartastotales.getInt("valorataque")+"Mana"+Cartastotales.getInt("valormana")+"Vida"+Cartastotales.getInt("valorvida"));
            }
             /*Por ultimo si la conexion no es nula la cierra (y con ello tb los 
            Statements y Resultsets que creasemos con ella
            */
            try {
                if(conexion!=null){
                conexion.close();
                }
            } catch (SQLException ex) {
                Logger.getLogger(JuegoPruevas.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/local/DANIELCASTELAO/dfernandezrivas/NetBeansProjects/Proyecto2/ProyectoProgramacion/src/maagic/img/ImagenFondo.jpg")); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 1000));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
