/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maagic.interfaz;

/**
 *
 * @author Delio
 */
public class Jugar extends javax.swing.JPanel {

    /**
     * Creates new form Jugar
     */
    public Jugar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelManoJ1 = new javax.swing.JPanel();
        PanelManoJ2 = new javax.swing.JPanel();
        PanelTableroJ2 = new javax.swing.JPanel();
        PanelTableroJ1 = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout PanelManoJ1Layout = new javax.swing.GroupLayout(PanelManoJ1);
        PanelManoJ1.setLayout(PanelManoJ1Layout);
        PanelManoJ1Layout.setHorizontalGroup(
            PanelManoJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        PanelManoJ1Layout.setVerticalGroup(
            PanelManoJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );

        add(PanelManoJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 380, 910));

        javax.swing.GroupLayout PanelManoJ2Layout = new javax.swing.GroupLayout(PanelManoJ2);
        PanelManoJ2.setLayout(PanelManoJ2Layout);
        PanelManoJ2Layout.setHorizontalGroup(
            PanelManoJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        PanelManoJ2Layout.setVerticalGroup(
            PanelManoJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );

        add(PanelManoJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 70, 410, 910));

        javax.swing.GroupLayout PanelTableroJ2Layout = new javax.swing.GroupLayout(PanelTableroJ2);
        PanelTableroJ2.setLayout(PanelTableroJ2Layout);
        PanelTableroJ2Layout.setHorizontalGroup(
            PanelTableroJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        PanelTableroJ2Layout.setVerticalGroup(
            PanelTableroJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );

        add(PanelTableroJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 70, 410, 910));

        javax.swing.GroupLayout PanelTableroJ1Layout = new javax.swing.GroupLayout(PanelTableroJ1);
        PanelTableroJ1.setLayout(PanelTableroJ1Layout);
        PanelTableroJ1Layout.setHorizontalGroup(
            PanelTableroJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        PanelTableroJ1Layout.setVerticalGroup(
            PanelTableroJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );

        add(PanelTableroJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 380, 910));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelManoJ1;
    private javax.swing.JPanel PanelManoJ2;
    private javax.swing.JPanel PanelTableroJ1;
    private javax.swing.JPanel PanelTableroJ2;
    // End of variables declaration//GEN-END:variables
}
