/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maagic.interfaz;

/**
 *
 * @author Delio
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu2
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Boton1Jugar = new javax.swing.JButton();
        Boton2Baraja = new javax.swing.JButton();
        Boton3Salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Delio\\Documents\\NetBeansProjects\\ProyectoProgramacion\\src\\maagic\\interfaz\\serien_grosses_logo_239-Recuperado.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, 290));

        Boton1Jugar.setBackground(new java.awt.Color(102, 140, 144));
        Boton1Jugar.setFont(new java.awt.Font("Felix Titling", 0, 11)); // NOI18N
        Boton1Jugar.setForeground(new java.awt.Color(102, 0, 102));
        Boton1Jugar.setText("Jugar");
        Boton1Jugar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Boton1Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton1JugarActionPerformed(evt);
            }
        });
        getContentPane().add(Boton1Jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 360, 620, 60));

        Boton2Baraja.setBackground(new java.awt.Color(102, 140, 144));
        Boton2Baraja.setFont(new java.awt.Font("Felix Titling", 0, 11)); // NOI18N
        Boton2Baraja.setForeground(new java.awt.Color(0, 102, 102));
        Boton2Baraja.setText("Crear Baraja");
        Boton2Baraja.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Boton2Baraja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton2BarajaActionPerformed(evt);
            }
        });
        getContentPane().add(Boton2Baraja, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, 440, 50));

        Boton3Salir.setBackground(new java.awt.Color(102, 140, 144));
        Boton3Salir.setFont(new java.awt.Font("Felix Titling", 0, 11)); // NOI18N
        Boton3Salir.setForeground(new java.awt.Color(153, 0, 0));
        Boton3Salir.setText("Salir");
        Boton3Salir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Boton3Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton3SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Boton3Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 570, 200, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Delio\\Documents\\NetBeansProjects\\ProyectoProgramacion\\src\\maagic\\interfaz\\The-dragon-of-hell-liam-a-dragon-37509157-1920-1080.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton3SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton3SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Boton3SalirActionPerformed

    private void Boton1JugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton1JugarActionPerformed
        Interfaz2 Jugar = new Interfaz2();
        Jugar.setVisible(true);
    }//GEN-LAST:event_Boton1JugarActionPerformed

    private void Boton2BarajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton2BarajaActionPerformed
        Baraja Baraja = new Baraja();
        Baraja.setVisible(true);
    }//GEN-LAST:event_Boton2BarajaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton1Jugar;
    private javax.swing.JButton Boton2Baraja;
    private javax.swing.JButton Boton3Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
